"""End-to-end computation of the topological descriptors of a set of spectra."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from . import persistence
from .images import PersistenceImager

__all__ = [
    "DescriptorConfig",
    "compute_diagrams",
    "compute_diagrams_multi",
    "build_imagers",
    "estimate_noise",
    "Descriptors",
]


@dataclass
class DescriptorConfig:
    """Hyper-parameters of the topological pipeline.

    ``min_persistence`` separates genuine absorption bands from features
    generated by detector noise. A fixed value only works while the noise floor
    is fixed; with ``adaptive_threshold`` set, the threshold is instead placed
    at ``noise_factor`` standard deviations of the noise estimated from each
    spectrum, which keeps the diagram meaningful across acquisition conditions.
    """

    kind: str = "peaks"
    min_persistence: float = 2e-3
    max_features: int = 300
    resolution: int = 20
    sigma: float | None = None
    sigma_wavenumber: float = 25.0
    adaptive_threshold: bool = True
    noise_factor: float = 4.0


def estimate_noise(spectrum: np.ndarray) -> float:
    """Robust estimate of the white-noise standard deviation of a spectrum.

    Uses the median absolute deviation of the second difference, which is
    insensitive to the smooth part of the signal: for white noise of standard
    deviation ``s`` the second difference has standard deviation ``s * sqrt(6)``.
    """
    d2 = np.diff(np.asarray(spectrum, dtype=float), n=2)
    if d2.size == 0:
        return 0.0
    mad = np.median(np.abs(d2 - np.median(d2)))
    return float(1.4826 * mad / np.sqrt(6.0))


@dataclass
class Descriptors:
    """Diagrams and their two vectorisations for a set of spectra."""

    diagrams: list[np.ndarray]
    lifetimes: list[np.ndarray]
    fingerprints: list[np.ndarray]
    n_features_raw: list[int]
    thresholds: list[float]


def compute_diagrams(
    intensity: np.ndarray, wavenumber: np.ndarray, config: DescriptorConfig
) -> Descriptors:
    """Persistence diagrams of every spectrum, in both coordinate systems."""
    return compute_diagrams_multi(intensity, wavenumber, [config])[0]


def compute_diagrams_multi(
    intensity: np.ndarray, wavenumber: np.ndarray, configs: list[DescriptorConfig]
) -> list[Descriptors]:
    """Descriptors for several pruning settings, sharing one persistence pass.

    Computing the diagram is by far the dominant cost, and it does not depend on
    the pruning parameters, so a comparison of thresholds should never pay for
    it twice. All configurations must agree on ``kind``.
    """
    if len({c.kind for c in configs}) != 1:
        raise ValueError("all configurations must share the same filtration kind")

    out = [Descriptors([], [], [], [], []) for _ in configs]

    for spectrum in np.atleast_2d(intensity):
        full, born_at, _ = persistence.spectrum_diagram(
            spectrum, kind=configs[0].kind, return_locations=True
        )
        noise = estimate_noise(spectrum)

        for config, descriptors in zip(configs, out):
            threshold = config.min_persistence
            if config.adaptive_threshold:
                threshold = max(threshold, config.noise_factor * noise)

            pruned, pruned_at = persistence.prune_diagram(
                full, threshold, config.max_features, birth_index=born_at
            )
            descriptors.n_features_raw.append(len(full))
            descriptors.thresholds.append(threshold)
            descriptors.diagrams.append(pruned)
            descriptors.lifetimes.append(persistence.lifetime_diagram(pruned))
            descriptors.fingerprints.append(
                persistence.position_lifetime_diagram(pruned, pruned_at, wavenumber)
            )

    return out


def build_imagers(
    descriptors: Descriptors, config: DescriptorConfig
) -> tuple[PersistenceImager, PersistenceImager]:
    """Fit the two image grids on a reference set of diagrams.

    The same fitted grids must then be reused for any further set of spectra
    (for instance perturbed copies), otherwise the resulting vectors are not
    comparable.
    """
    imager = PersistenceImager(resolution=config.resolution, sigma=config.sigma)
    imager.fit(descriptors.lifetimes)

    lifetime_pixel = imager.lifetime_range[1] / config.resolution
    fingerprint_imager = PersistenceImager(
        resolution=config.resolution,
        sigma=(config.sigma_wavenumber, max(lifetime_pixel, 1e-6)),
    )
    fingerprint_imager.fit(descriptors.fingerprints)

    return imager, fingerprint_imager
